### ISSUE TITLE
H12a - Criação da aplicação utilizando framework - Início

### ISSUE THREAD

**Issue by Mmichelefreitas** [ICEI-PUC-Minas-PMV-SInt/pmv-sint-2023-2-e3-proj-back-t1-projeto-ampare#43]
Avaliar e utilizar Frameworks Web Back-end: usar o framework ASP.NET  MVC para criar a aplicação baseada em camadas aplicando tipo de filtros do ASP.NET MVC, controllers e actions assíncronas.

**Comment by nickwulk** [comment]
@Matheus-9 vou puxar esse card pra mim pra te dar uma força na inicialização do projeto, ok?
